# Generated by Django 5.0.11 on 2026-04-12 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código de invitación')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email del invitado')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del invitado')),
                ('message', models.TextField(blank=True, max_length=500, verbose_name='Mensaje personal')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('ACEPTADA', 'Aceptada'), ('EXPIRADA', 'Expirada'), ('REVOCADA', 'Revocada')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='Invitado por')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_used', to=settings.AUTH_USER_MODEL, verbose_name='Usado por')),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvitationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('profile_type', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('PAREJA', 'Pareja')], default='HOMBRE', max_length=20, verbose_name='Tipo de perfil')),
                ('message', models.TextField(blank=True, max_length=500, verbose_name='¿Por qué quieres unirte?')),
                ('age_confirmed', models.BooleanField(default=False, verbose_name='Confirma ser mayor de 18')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Acepta términos y condiciones')),
                ('referral_code', models.CharField(blank=True, max_length=100, verbose_name='Código de referido (opcional)')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('LISTA_ESPERA', 'Lista de espera')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del admin')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de acceso',
                'verbose_name_plural': 'Solicitudes de acceso',
                'ordering': ['-created_at'],
            },
        ),
    ]
