# Generated by Django 5.0.11 on 2026-05-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAdmin',
            fields=[
                ('supabase_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('user_nick', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20)),
                ('visibility', models.CharField(default='public', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto (Admin)',
                'verbose_name_plural': 'Fotos (Admin)',
                'db_table': 'gallery_admin_mirror',
            },
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
