# Generated by Django 5.0.11 on 2026-04-12 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('plan_type', models.CharField(choices=[('GRATIS', 'Acceso libre'), ('BASICO', 'Básico'), ('VIP', 'VIP'), ('ELITE', 'Élite')], max_length=10, unique=True, verbose_name='Tipo')),
                ('price_mxn', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio MXN')),
                ('price_mxn_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio mensual MXN')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('features', models.JSONField(default=list, verbose_name='Características')),
                ('max_photos', models.PositiveIntegerField(default=5, verbose_name='Máx fotos')),
                ('max_videos', models.PositiveIntegerField(default=0, verbose_name='Máx videos')),
                ('max_messages_per_day', models.PositiveIntegerField(default=10, verbose_name='Mensajes/día')),
                ('can_view_private_photos', models.BooleanField(default=False)),
                ('can_send_invitations', models.BooleanField(default=False)),
                ('can_join_events', models.BooleanField(default=False)),
                ('can_create_events', models.BooleanField(default=False)),
                ('profile_badge', models.CharField(blank=True, max_length=50, verbose_name='Insignia')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plan de membresía',
                'verbose_name_plural': 'Planes de membresía',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('EXPIRADO', 'Expirado'), ('CANCELADO', 'Cancelado'), ('GRACIA', 'Período de gracia')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('starts_at', models.DateTimeField(verbose_name='Inicio')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Renovación automática')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memberships.membershipplan', verbose_name='Plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Membresía de usuario',
                'verbose_name_plural': 'Membresías de usuarios',
            },
        ),
    ]
