# Generated by Django 5.0.11 on 2026-04-12 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('PAREJA', 'Pareja')], default='HOMBRE', max_length=20, verbose_name='Tipo de perfil')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente de verificación'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('BANEADO', 'Baneado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='Apodo')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(blank=True, max_length=20, verbose_name='Género')),
                ('partner_nickname', models.CharField(blank=True, max_length=50, verbose_name='Apodo de pareja')),
                ('partner_birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha nacimiento pareja')),
                ('partner_gender', models.CharField(blank=True, max_length=20, verbose_name='Género pareja')),
                ('state', models.CharField(blank=True, choices=[('AGS', 'Aguascalientes'), ('BC', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAMP', 'Campeche'), ('CHIS', 'Chiapas'), ('CHIH', 'Chihuahua'), ('CDMX', 'Ciudad de México'), ('COAH', 'Coahuila'), ('COL', 'Colima'), ('DGO', 'Durango'), ('GTO', 'Guanajuato'), ('GRO', 'Guerrero'), ('HGO', 'Hidalgo'), ('JAL', 'Jalisco'), ('MEX', 'Estado de México'), ('MICH', 'Michoacán'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NL', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QRO', 'Querétaro'), ('QROO', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAMS', 'Tamaulipas'), ('TLAX', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], max_length=10, verbose_name='Estado')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='Preferencias')),
                ('looking_for', models.CharField(blank=True, max_length=200, verbose_name='Busco')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/', verbose_name='Avatar')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='profiles/covers/', verbose_name='Foto de portada')),
                ('is_private', models.BooleanField(default=True, verbose_name='Perfil privado')),
                ('show_location', models.BooleanField(default=False, verbose_name='Mostrar ubicación')),
                ('show_age', models.BooleanField(default=True, verbose_name='Mostrar edad')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('connections_count', models.PositiveIntegerField(default=0, verbose_name='Conexiones')),
                ('age_verified', models.BooleanField(default=False, verbose_name='Edad verificada')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Términos aceptados')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lobby69_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('BLOQUEADO', 'Bloqueado')], default='PENDIENTE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_sent', to='profiles.profile', verbose_name='De')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_received', to='profiles.profile', verbose_name='Para')),
            ],
            options={
                'verbose_name': 'Conexión',
                'verbose_name_plural': 'Conexiones',
                'unique_together': {('from_profile', 'to_profile')},
            },
        ),
    ]
