# Generated by Django 5.0.11 on 2026-04-12 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APROBAR', 'Aprobó contenido'), ('RECHAZAR', 'Rechazó contenido'), ('SUSPENDER', 'Suspendió usuario'), ('BANEAR', 'Baneó usuario'), ('ADVERTIR', 'Advirtió usuario'), ('RESTAURAR', 'Restauró contenido')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de moderación',
                'verbose_name_plural': 'Logs de moderación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('MENOR_EDAD', 'Contenido con menores de edad'), ('SPAM', 'Spam o contenido no deseado'), ('ACOSO', 'Acoso o intimidación'), ('PERFIL_FALSO', 'Perfil falso'), ('INAPROPIADO', 'Contenido inapropiado'), ('OTRO', 'Otro')], max_length=15, verbose_name='Motivo')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('RESUELTO', 'Resuelto'), ('DESCARTADO', 'Descartado')], default='PENDIENTE', max_length=12, verbose_name='Estado')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('moderator_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
    ]
