# Generated by Django 5.0.11 on 2026-04-12 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TEXTO', 'Texto'), ('IMAGEN', 'Imagen'), ('AUDIO', 'Audio'), ('STICKER', 'Sticker')], default='TEXTO', max_length=10)),
                ('content', models.TextField(blank=True, max_length=2000, verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='messages/images/%Y/%m/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='messages/audio/%Y/%m/')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted_sender', models.BooleanField(default=False)),
                ('is_deleted_receiver', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='private_messaging.conversation', verbose_name='Conversación')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['created_at'],
            },
        ),
    ]
