# Generated by Django 5.0.11 on 2026-04-12 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('plan_type', models.CharField(choices=[('TORNEO', 'Torneo'), ('NOCHE_TEMATICA', 'Noche temática'), ('EVENTO_PRIVADO', 'Evento privado'), ('TALLER', 'Taller'), ('REUNIÓN', 'Reunión')], default='TORNEO', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora fin')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lugar')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('is_members_only', models.BooleanField(default=True)),
                ('min_membership', models.CharField(blank=True, max_length=10, verbose_name='Membresía mínima')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plans/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan del día',
                'verbose_name_plural': 'Planes del día',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('TEXTO', 'Texto'), ('FOTO', 'Foto'), ('VIDEO', 'Video'), ('EVENTO', 'Evento'), ('STORY', 'Story'), ('ENCUESTA', 'Encuesta')], default='TEXTO', max_length=10, verbose_name='Tipo')),
                ('content', models.TextField(blank=True, max_length=2000, verbose_name='Contenido')),
                ('visibility', models.CharField(choices=[('PUBLICO', 'Público (miembros)'), ('CONEXIONES', 'Solo conexiones'), ('PRIVADO', 'Solo yo')], default='PUBLICO', max_length=12, verbose_name='Visibilidad')),
                ('image', models.ImageField(blank=True, null=True, upload_to='feed/images/%Y/%m/', verbose_name='Imagen')),
                ('video', models.FileField(blank=True, null=True, upload_to='feed/videos/%Y/%m/', verbose_name='Video')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('is_nsfw', models.BooleanField(default=False, verbose_name='Contenido adulto')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='Comentario')),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social_feed.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social_feed.post')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/%Y/%m/')),
                ('video', models.FileField(blank=True, null=True, upload_to='stories/videos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_nsfw', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expira')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('LIKE', '👍 Me gusta'), ('FUEGO', '🔥 Fuego'), ('CORAZON', '❤️ Me encanta'), ('WOW', '😮 Wow')], default='LIKE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social_feed.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reacción',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
