# Generated by Django 5.0.11 on 2026-04-12 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('INE', 'INE / Credencial'), ('PASAPORTE', 'Pasaporte'), ('LICENCIA', 'Licencia de conducir'), ('SELFIE_ID', 'Selfie con ID')], max_length=15, verbose_name='Método')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('REENVIAR', 'Reenviar documentos')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('document_front', models.ImageField(blank=True, null=True, upload_to='verification/documents/%Y/%m/', verbose_name='Documento (frente)')),
                ('document_back', models.ImageField(blank=True, null=True, upload_to='verification/documents/%Y/%m/', verbose_name='Documento (reverso)')),
                ('selfie_with_id', models.ImageField(blank=True, null=True, upload_to='verification/selfies/%Y/%m/', verbose_name='Selfie con ID')),
                ('declared_birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento declarada')),
                ('declared_name', models.CharField(blank=True, max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo de rechazo')),
                ('consent_given', models.BooleanField(default=False, verbose_name='Consentimiento dado')),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='age_verification', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Verificación de edad',
                'verbose_name_plural': 'Verificaciones de edad',
                'ordering': ['-created_at'],
            },
        ),
    ]
