# Generated by Django 5.0.11 on 2026-04-17 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('edad', models.IntegerField()),
                ('ciudad', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=50)),
                ('tipo_perfil', models.CharField(choices=[('individual', 'Individual'), ('pareja', 'Pareja'), ('grupo', 'Grupo')], max_length=50)),
                ('mensaje', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('terminos_aceptados', models.BooleanField(default=False)),
                ('privacidad_aceptada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('activation_token', models.CharField(blank=True, max_length=255, unique=True)),
                ('activation_used', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Invitación',
                'verbose_name_plural': 'Solicitudes de Invitación',
                'db_table': 'invitation_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
