# Generated by Django 5.0.11 on 2026-04-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationrequest',
            old_name='mensaje',
            new_name='motivo',
        ),
        migrations.RenameField(
            model_name='invitationrequest',
            old_name='ciudad',
            new_name='municipio',
        ),
        migrations.RemoveField(
            model_name='invitationrequest',
            name='genero',
        ),
        migrations.AddField(
            model_name='invitationrequest',
            name='estado',
            field=models.CharField(choices=[('aguascalientes', 'Aguascalientes'), ('baja_california', 'Baja California'), ('baja_california_sur', 'Baja California Sur'), ('campeche', 'Campeche'), ('coahuila', 'Coahuila'), ('colima', 'Colima'), ('chiapas', 'Chiapas'), ('chihuahua', 'Chihuahua'), ('cdmx', 'Ciudad de México'), ('durango', 'Durango'), ('guanajuato', 'Guanajuato'), ('guerrero', 'Guerrero'), ('hidalgo', 'Hidalgo'), ('jalisco', 'Jalisco'), ('mexico', 'Estado de México'), ('michoacan', 'Michoacán'), ('morelos', 'Morelos'), ('nayarit', 'Nayarit'), ('nuevo_leon', 'Nuevo León'), ('oaxaca', 'Oaxaca'), ('puebla', 'Puebla'), ('queretaro', 'Querétaro'), ('quintana_roo', 'Quintana Roo'), ('san_luis_potosi', 'San Luis Potosí'), ('sinaloa', 'Sinaloa'), ('sonora', 'Sonora'), ('tabasco', 'Tabasco'), ('tamaulipas', 'Tamaulipas'), ('tlaxcala', 'Tlaxcala'), ('veracruz', 'Veracruz'), ('yucatan', 'Yucatán'), ('zacatecas', 'Zacatecas')], default='México', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitationrequest',
            name='pais',
            field=models.CharField(default='Mexico', max_length=50),
        ),
        migrations.AlterField(
            model_name='invitationrequest',
            name='tipo_perfil',
            field=models.CharField(choices=[('single', 'Single'), ('unicornio', 'Unicornio'), ('pareja', 'Pareja')], max_length=50),
        ),
    ]
