# Generated by Django 5.0.11 on 2026-04-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_rename_mensaje_invitationrequest_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationrequest',
            name='invited_by',
            field=models.CharField(blank=True, help_text='Email o nick de quien invitó', max_length=255, null=True),
        ),
    ]
