# Generated by Django 5.0.11 on 2026-04-28 04:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_invitationrequest_invited_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'photo_albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'photo_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='invitationrequest',
            name='estado',
            field=models.CharField(choices=[('aguascalientes', 'Aguascalientes'), ('baja_california', 'Baja California'), ('cdmx', 'Ciudad de México')], max_length=50),
        ),
        migrations.AlterField(
            model_name='invitationrequest',
            name='invited_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PhotoLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'photo_likes',
                'unique_together': {('photo_id', 'user_id')},
            },
        ),
    ]
