# Generated by Django 5.0.11 on 2026-04-12 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Referencia')),
                ('amount_mxn', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto MXN')),
                ('method', models.CharField(choices=[('TARJETA', 'Tarjeta de crédito/débito'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('OXXO', 'OXXO Pay'), ('PAYPAL', 'PayPal'), ('CRIPTO', 'Criptomoneda')], max_length=15, verbose_name='Método de pago')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('REEMBOLSADO', 'Reembolsado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=12, verbose_name='Estado')),
                ('provider_ref', models.CharField(blank=True, max_length=255, verbose_name='Referencia del proveedor')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='Respuesta del proveedor')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='payments/receipts/%Y/%m/', verbose_name='Comprobante')),
                ('receipt_verified', models.BooleanField(default=False)),
                ('receipt_verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memberships.membershipplan', verbose_name='Plan')),
                ('receipt_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
